name = "brandapi"
main = "src/index.ts"
compatibility_date = "2026-08-02"

[vars]
# Pas dit aan zodra GitHub Pages voor dit repo aanstaat, bv:
# https://<jouw-github-gebruikersnaam>.github.io/BrandAPI
DATA_BASE_URL = "https://captainyannick.github.io/BrandAPI/brands.json"
